apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "my-app.fullname" . }}-config
  labels:
    {{- include "my-app.labels" . | nindent 4 }}
data:
  appName: {{ .Values.config.appName | quote }}
  environment: {{ .Values.config.environment | quote }}